sudo: false
language: node_js
node_js:
  - '12.7'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn global add jest
  - (cd server && npm run test:unit)
  - (cd webapp && npm run test:unit)
#  - npm run coveralls
