sudo: false
language: node_js
node_js:
  - '12.7'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn global add jest
  - (cd server && yarn && npm run test:unit)
  - (cd webapp && yarn && npm run test:unit)
#  - npm run coveralls

notifications:
  slack: mbari:8pk8atilpwNYAjspmOjRmZ3N
