version: '3.6'
services:
  mxm:
    container_name: mxm

    # NOTE: sometimes pushed with "latest" as default for convenience, especially during prototyping.
    # General recommendation is to use explicit version on actual deployment.
    image: mbari/mxm:0.6.0

    volumes:
      - ${MXM_CONFIG_DIR}:/mxm/dist/spa/statics/config
    ports:
    - "38080:3000"

    environment:
      PG_CONN_STRING: postgres://mxm@mxm-postgres:5432/mxm

    depends_on:
    - mxm-postgres
    restart: always

  mxm-postgres:
    container_name: mxm-postgres
    image: mbari/mxm-postgres:0.5.2
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # POSTGRES_USER: will trigger the creation of the "mxm" user
      # and "mxm" database upon initial run of the container:
      POSTGRES_USER: mxm
