version: '3.6'
services:
  mxm:
    container_name: mxm

    # NOTE: "latest" as default for convenience, especially during prototyping.
    # General recommendation is to use explicit version on actual deployment.
    image: mbari/mxm:latest

    volumes:
      - ${MXM_CONFIG_DIR}:/mxm/statics/config
    ports:
    - "38080:4000"
    depends_on:
    - mxm-postgraphile
    restart: always

  mxm-postgraphile:
    container_name: mxm-postgraphile
    image: graphile/postgraphile:4
    ports:
    - "5000:5000"
    depends_on:
    - mxm-postgres
    restart: always
    command:
      - --connection
      - postgresql://mxm@mxm-postgres:5432/mxm
      - --schema
      - public
      - --cors
      - --simple-collections
      - only
      - --classic-ids
      - --graphql
      - /mxm-graphql
      - --graphiql
      - /mxm-graphiql
      - --enhance-graphiql
      - --export-schema-graphql
      - mxmExportedSchema.graphql

  mxm-postgres:
    container_name: mxm-postgres
    image: mbari/mxm-postgres:0.4.0
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # POSTGRES_USER: will trigger the creation of the "mxm" user
      # and "mxm" database upon initial run of the container:
      POSTGRES_USER: mxm
