version: '3.6'
services:
  pxs-ui:
    image: mbari/pxs-ui:0.0.1
    ports:
    - "38080:80"
    depends_on:
    - graphql-engine
    restart: always

  graphql-engine:
    image: graphile/postgraphile
    ports:
    - "5000:5000"
    depends_on:
    - "pxspostgres"
    restart: always
    command:
      - --connection
      - postgresql://pxs@pxspostgres:5432/pxs
      - --schema
      - public
      - --cors
      - --simple-collections
      - only

  pxspostgres:
    image: mbari/pxspostgres:0.0.1
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data

    environment:
      # will trigger the creation of the "pxs" user and database:
      POSTGRES_USER: pxs

volumes:
  db_data:
