version: '3.6'
services:
  mxm:
    container_name: mxm
    image: mbari/mxm:0.2.1
    ports:
    - "38080:80"
    depends_on:
    - graphql-engine
    restart: always

  graphql-engine:
    container_name: mxm-postgraphile
    image: graphile/postgraphile
    ports:
    - "5000:5000"
    depends_on:
    - mxm-postgres
    restart: always
    command:
      - --connection
      - postgresql://mxm@mxm-postgres:5432/mxm
      - --schema
      - public
      - --cors
      - --simple-collections
      - only
      - --classic-ids
      - --graphql
      - /mxm-graphql
      - --graphiql
      - /mxm-graphiql

  mxm-postgres:
    container_name: mxm-postgres
    image: mbari/mxm-postgres:0.2.1
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # will trigger the creation of the "mxm" user and database:
      # upon initial run of the container:
      POSTGRES_USER: mxm
