version: '3.6'
services:
  mxms:
    container_name: mxms
    image: mbari/mxms:0.2.0
    ports:
    - "38080:80"
    depends_on:
    - graphql-engine
    restart: always

  graphql-engine:
    container_name: postgraphile
    image: graphile/postgraphile
    ports:
    - "5000:5000"
    depends_on:
    - mxmspostgres
    restart: always
    command:
      - --connection
      - postgresql://mxms@mxmspostgres:5432/mxms
      - --schema
      - public
      - --cors
      - --simple-collections
      - only
      - --classic-ids
      - --graphql
      - /mxms-graphql
      - --graphiql
      - /mxms-graphiql

  mxmspostgres:
    container_name: mxmspostgres
    image: mbari/mxmspostgres:0.2.0
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # will trigger the creation of the "mxms" user and database:
      POSTGRES_USER: mxms
