version: '3.6'
services:
  mxm:
    container_name: mxm
    image: mbari/mxm:0.3.5
    volumes:
      - ${MXM_CONFIG_DIR}:/usr/local/apache2/htdocs/statics/config
    ports:
    - "38080:80"
    depends_on:
    - graphql-engine
    restart: always

  graphql-engine:
    container_name: mxm-postgraphile
    image: graphile/postgraphile:4
    ports:
    - "5000:5000"
    depends_on:
    - mxm-postgres
    restart: always
    command:
      - --connection
      - postgresql://mxm@mxm-postgres:5432/mxm
      - --schema
      - public
      - --cors
      - --simple-collections
      - only
      - --classic-ids
      - --graphql
      - /mxm-graphql
      - --graphiql
      - /mxm-graphiql
      - --export-schema-graphql
      - mxmExportedSchema.graphql

  mxm-postgres:
    container_name: mxm-postgres
    image: mbari/mxm-postgres:0.3.5
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # POSTGRES_USER: will trigger the creation of the "mxm" user
      # and "mxm" database upon initial run of the container:
      POSTGRES_USER: mxm
