version: '3.6'
services:
  pxs:
    container_name: pxs
    image: mbari/pxs:0.0.7
    ports:
    - "38080:80"
    depends_on:
    - graphql-engine
    restart: always

  graphql-engine:
    container_name: postgraphile
    image: graphile/postgraphile
    ports:
    - "5000:5000"
    depends_on:
    - pxspostgres
    restart: always
    command:
      - --connection
      - postgresql://pxs@pxspostgres:5432/pxs
      - --schema
      - public
      - --cors
      - --simple-collections
      - only
      - --classic-ids
      - --graphql
      - /pxs-graphql
      - --graphiql
      - /pxs-graphiql

  pxspostgres:
    container_name: pxspostgres
    image: mbari/pxspostgres:0.0.7
    ports:
    - "25432:5432"
    restart: always
    volumes:
    - ${PWD}/db_data:/var/lib/postgresql/data

    environment:
      # will trigger the creation of the "pxs" user and database:
      POSTGRES_USER: pxs
