mutation createAssetClass($providerId:String!, $className: String!, $description: String) {
  createAssetClass(
    input: {
      assetClass: {
        providerId: $providerId
        className: $className
        description: $description
      }
    }
  ) {
    assetClass {
      providerId
      className
      description
    }
  }
}
