mutation createMissionTpl(
  $providerId: String!
  $missionTplId: String!
  $description: String
  $retrievedAt: Datetime
) {
  createMissionTpl(
    input: {
      missionTpl: {
        providerId: $providerId
        missionTplId: $missionTplId
        description: $description
        retrievedAt: $retrievedAt
      }
    }
  ) {
    missionTpl {
      providerId
      missionTplId
      description
      retrievedAt
    }
  }
}
