mutation createParameter(
  $providerId: String!
  $missionTplId: String!
  $paramName: String!
  $type: String!
  $required: Boolean!
  $defaultValue: String
  $defaultUnits: String
  $valueCanReference: String
  $description: String
) {
  createParameter(
    input: {
      parameter: {
        providerId: $providerId
        missionTplId: $missionTplId
        description: $description
        paramName: $paramName
        type: $type
        defaultValue: $defaultValue
        defaultUnits: $defaultUnits
        valueCanReference: $valueCanReference
        required: $required
      }
    }
  ) {
    parameter {
      providerId
      missionTplId
      description
      paramName
      type
      defaultValue
      defaultUnits
      valueCanReference
      required
    }
  }
}
