mutation(
  $missionId: String!
  $executorId: String!
  $missionDefId: String!
  $paramName: String!
  $paramValue: String!
) {
  createArgument(
    input: {
      argument: {
        missionId: $missionId
        executorId: $executorId
        missionDefId: $missionDefId
        paramName: $paramName
        paramValue: $paramValue
      }
    }
  ) {
    argument {
      missionId
      executorId
      missionDefId
      paramName
      paramValue
    }
  }
}
