mutation deleteArgument($input: DeleteArgumentInput!) {
  deleteArgument(input: $input) {
    argument {
      missionId
      executorId
      missionDefId
      paramName
      paramValue
    }
  }
}

#variables: {
#  "input": {
#    "id": ""
#  }
#}
