mutation(
  $taskId: String!
  $executorId: String!
  $taskDefId: String!
  $paramName: String!
  $paramValue: String!
) {
  createArgument(
    input: {
      argument: {
        taskId: $taskId
        executorId: $executorId
        taskDefId: $taskDefId
        paramName: $paramName
        paramValue: $paramValue
      }
    }
  ) {
    argument {
      taskId
      executorId
      taskDefId
      paramName
      paramValue
    }
  }
}
