query arguments(
  $planId: String!,
  $taskId: String!
) {
  arguments(where: {
    planId: {_eq: $planId},
    taskId: {_eq: $taskId}
  }) {
    planId
    taskId
    executorId
    taskDefId
    paramName
    paramValue
  }
}
