mutation(
  $missionId: String!
  $executorId: String!
  $missionTplId: String!
  $paramName: String!
  $paramValue: String!
) {
  createArgument(
    input: {
      argument: {
        missionId: $missionId
        executorId: $executorId
        missionTplId: $missionTplId
        paramName: $paramName
        paramValue: $paramValue
      }
    }
  ) {
    argument {
      missionId
      executorId
      missionTplId
      paramName
      paramValue
    }
  }
}
