mutation($executorId:String!, $className: String!, $description: String) {
  createAssetClass(
    input: {
      assetClass: {
        executorId: $executorId
        className: $className
        description: $description
      }
    }
  ) {
    assetClass {
      executorId
      className
      description
    }
  }
}
