query assets($executorId: String!) {
  allAssetsList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    assetClassByExecutorIdAndClassName {
      executorByExecutorId {
        descriptionFormat
      }
    }
    className
    assetId
    description
  }
}
