query ($assetId: String!) {
  allAssetsList(condition: {
    assetId: $assetId
  }) {
    assetClassByExecutorIdAndClassName {
      executorByExecutorId {
        descriptionFormat
      }
    }
    id
    assetId
    className
    description
  }
}
