query ($className: String!) {
  allAssetClassesList(condition: {
    className: $className
  }) {
    className
    description
    assetsByClassNameList {
      assetId
      description
    }
  }
}
