mutation($executorId: String!, $className: String!, $assetId: String!, $description: String) {
  createAsset(
    input: {
      asset: {
        executorId: $executorId
        className: $className
        assetId: $assetId
        description: $description
      }
    }
  ) {
    asset {
      executorId
      className
      assetId
      description
    }
  }
}
