mutation($asset_id: String!, $className: String!, $description: String) {
  insert_assets(
    objects: [
      {
        asset_id: $asset_id,
        className: $className,
        description: $description
      }
    ]
  ) {
    affected_rows
  }
}
