mutation($assetId: String!, $className: String!, $description: String) {
  createAsset(
    input: {
      asset: {
        assetId: $assetId
        className: $className
        description: $description
      }
    }
  ) {
    asset {
      assetId
      className
      description
    }
  }
}
