query ($executorId: String!, $className: String!) {
  allAssetClassesList(condition: {
    executorId:$executorId,
    className: $className
  }) {
    id
    executorId
    executorByExecutorId {
      descriptionFormat
    }
    className
    description
    assetsByExecutorIdAndClassNameList {
      assetId
      description
    }
  }
}
