mutation($className: String!, $description: String) {
  createAssetClass(
    input: {
      assetClass: {
        className: $className
        description: $description
      }
    }
  ) {
    assetClass {
      className
      description
    }
  }
}
