mutation($providerId: String!, $className: String!, $assetId: String!, $description: String) {
  createAsset(
    input: {
      asset: {
        providerId: $providerId
        className: $className
        assetId: $assetId
        description: $description
      }
    }
  ) {
    asset {
      providerId
      className
      assetId
      description
    }
  }
}
