query assetClasses($executorId: String!) {
  allAssetClassesList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    executorByExecutorId {
      descriptionFormat
    }
    className
    description
  }
}
