mutation updateAssetClass($input: UpdateAssetClassInput!) {
  updateAssetClass(input: $input) {
    assetClass {
      id
      className
      description
      assetsByExecutorIdAndClassNameList {
        assetId
      }
    }
  }
}

# variables: {
#  "input": {
#    "id": "..",
#    "assetClassPatch": {
#      "description": "new description.."
#    }
#  }
#}
