mutation($assetId: String!, $assetClass: String!, $description: String) {
  insert_asset(
    objects: [
      {
        assetId: $assetId,
        assetClass: $assetClass,
        description: $description
      }
    ]
  ) {
    affected_rows
  }
}
