mutation($executorId: String!, $httpEndpoint: String!, $description: String) {
  insert_executors(
    objects: [
      {
        executorId: $executorId
        httpEndpoint: $httpEndpoint
        description: $description
      }
    ]
  ) {
    affected_rows
  }
}
