mutation($executorId: String!, $assetClassName: String!) {
  insert_executor_assetclass(
    objects: [
      { executorId: $executorId, assetClassName: $assetClassName}
    ]
  ) {
    affected_rows
  }
}
