{
  allExecutors {
    nodes {
      nodeId
      executorId
      httpEndpoint
      description
      executorAssetClassesByExecutorId {
        nodes {
          assetClassName
        }
      }
    }
  }
}
