query executor($executorId: String!) {
  allExecutorsList(condition: {
    executorId: $executorId
  }) {
    nodeId
    executorId
    httpEndpoint
    description
    missionDefsByExecutorIdList {
      nodeId
      missionDefId
      description
      missionDefAssetClassesByExecutorIdAndMissionDefIdList {
        assetClassName
        assetClassByAssetClassName {
          assetsByClassNameList {
            assetId
          }
        }
      }
    }
  }
}
