query executor($executorId: String!) {
  executors(where: {executorId: {_eq: $executorId}}) {
    executorId
    httpEndpoint
    description
    executorAssetsByexecutorid {
      assetId
      assetsByassetid {
        assetClass
        description
      }
    }
  }
}
