mutation($executorId: String!, $asset_className: String!) {
  delete_executor_asset_class(where: {
    _and: [
      {executorId:     {_eq: $executorId}},
      {asset_className: {_eq: $asset_className}}
    ]
  }) {
    affected_rows
  }
}
