query executor($executorId: String!) {
  allExecutorsList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    httpEndpoint
    description
    missionDefsByExecutorIdList {
      id
      missionDefId
      description
      missionDefAssetClassesByExecutorIdAndMissionDefIdList {
        assetClassName
        assetClassByExecutorIdAndAssetClassName {
          assetsByExecutorIdAndClassNameList {
            assetId
          }
        }
      }
    }
  }
}
