mutation updateMission($input: UpdateMissionInput!) {
  updateMission(input: $input) {
    mission {
      id
      missionId
      executorId
      missionDefId
      description
      assetId
      startDate
      endDate
      geometry
    }
  }
}


# variables: {
#  "input": {
#    "id": "WyJtaXNzaW9ucyIsInNjaTJpbnN0MiJd",
#    "missionPatch": {
#      "description": "updated description ..."
#    }
#  }
#}
