query mission($executorId: String!, $missionTplId: String!, $missionId: String!) {
  missionByExecutorIdAndMissionTplIdAndMissionId(
    executorId: $executorId,
    missionTplId: $missionTplId,
    missionId: $missionId
  ) {
    id
    executorId
    missionTplId
    missionId
    missionStatus
    assetId
    assetByExecutorIdAndAssetId {
      className
    }
    description
    argumentsByExecutorIdAndMissionTplIdAndMissionIdList {
      id
      paramName
      paramValue
      paramUnits
      parameterByExecutorIdAndMissionTplIdAndParamName {
        type
        required
        defaultValue
        defaultUnits
        description
      }
    }
    missionTplByExecutorIdAndMissionTplId {
      executorByExecutorId {
        httpEndpoint
        apiType
        canValidate
        usesUnits
        descriptionFormat
      }
      parametersByExecutorIdAndMissionTplIdList(orderBy: PARAM_ORDER_ASC) {
        paramName
        type
        valueCanReference
        required
        defaultValue
        defaultUnits
        description
      }
    }
  }
}
