mutation deleteMission($input: DeleteMissionInput!) {
  deleteMission(input: $input) {
    mission {
      id
      executorId
      missionTplId
      missionId
      description
      assetId
    }
  }
}
#    {
#      "input": {
#        "id": ".."
#      }
#    }
