query missionDefs($executorId: String!) {
  allMissionDefsList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    missionDefId
    description
    missionDefAssetClassesByExecutorIdAndMissionDefIdList {
      assetClassName
      assetClassByExecutorIdAndAssetClassName {
        assetsByExecutorIdAndClassNameList {
          assetId
        }
      }
    }
  }
}
