mutation updateMissionTpl($input: UpdateMissionTplInput!) {
  updateMissionTpl(input: $input) {
    missionTpl {
      id
      providerId
      missionTplId
      description
    }
  }
}

# variables: {
#  "input": {
#    "id": "..",
#    "missionTplPatch": {
#      "description": "updated description ..."
#      "missionTplId": ".."
#    }
#  }
#}
