query ($executorId: String!, $missionDefId: String!) {
  missionDefByExecutorIdAndMissionDefId(executorId: $executorId, missionDefId: $missionDefId) {
    nodeId
    missionDefId
    description
    missionDefAssetClassesByExecutorIdAndMissionDefIdList {
      nodeId
      assetClassName
      assetClassByExecutorIdAndAssetClassName {
        description
      }
    }
    parametersByExecutorIdAndMissionDefIdList {
      nodeId
      name
      type
      required
      defaultValue
      description
    }
  }
}
