query ($executorId: String!, $missionDefId: String!) {
  missionDefByExecutorIdAndMissionDefId(executorId: $executorId, missionDefId: $missionDefId) {
    id
    missionDefId
    description
    missionDefAssetClassesByExecutorIdAndMissionDefIdList {
      id
      assetClassName
      assetClassByExecutorIdAndAssetClassName {
        description
      }
    }
    parametersByExecutorIdAndMissionDefIdList {
      id
      name
      type
      required
      defaultValue
      description
    }
  }
}
