mutation(
  $missionId: String!
  $executorId: String!
  $missionDefId: String!
  $assetId: String!
  $description: String
) {
  createMission(
    input: {
      mission: {
        missionId: $missionId
        executorId: $executorId
        missionDefId: $missionDefId
        assetId: $assetId
        description: $description
      }
    }
  ) {
    mission {
      missionId
      executorId
      missionDefId
      assetId
      description
      startDate
      endDate
      geometry
    }
  }
}
