mutation(
  $executorId: String!
  $missionTplId: String!
  $description: String
) {
  createMissionTpl(
    input: {
      missionTpl: {
        executorId: $executorId
        missionTplId: $missionTplId
        description: $description
      }
    }
  ) {
    missionTpl {
      executorId
      missionTplId
      description
    }
  }
}
