mutation($input: CreateMissionInput!) {
  createMission(input: $input) {
    mission {
      executorId
      missionTplId
      missionId
      missionStatus
      assetId
      description
      startDate
      endDate
      geometry
    }
  }
}

#    {
#      "input": {
#        "mission": {
#          "executorId": "x1",
#          "missionTplId": "tft",
#          "missionId": "m1",
#          "assetId": "tiny",
#          "description": "foo",
#          "startDate": "-30m",
#          "missionStatus": "DRAFT"
#        }
#      }
#    }
