query missionTpls($executorId: String!) {
  allMissionTplsList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    missionTplId
    description
    missionTplAssetClassesByExecutorIdAndMissionTplIdList {
      assetClassName
      assetClassByExecutorIdAndAssetClassName {
        assetsByExecutorIdAndClassNameList {
          assetId
        }
      }
    }
  }
}
