mutation createMissionTplAssetClass($providerId: String!, $missionTplId: String!, $assetClassName: String!) {
  createMissionTplAssetClass(
    input: {
      missionTplAssetClass: {
        missionTplId: $missionTplId
        providerId: $providerId
        assetClassName: $assetClassName
      }
    }
  ) {
    missionTplAssetClass {
      providerId
      missionTplId
      assetClassName
    }
  }
}
