query mission($executorId: String!, $missionDefId: String!, $missionId: String!) {
  missionByExecutorIdAndMissionDefIdAndMissionId(
    executorId: $executorId,
    missionDefId: $missionDefId,
    missionId: $missionId
  ) {
    id
    executorId
    missionDefId
    missionId
    missionStatus
    assetId
    assetByExecutorIdAndAssetId {
      className
    }
    description
    argumentsByExecutorIdAndMissionDefIdAndMissionIdList {
      id
      paramName
      paramValue
      parameterByExecutorIdAndMissionDefIdAndParamName {
        type
        required
        defaultValue
        description
      }
    }
    missionDefByExecutorIdAndMissionDefId {
      parametersByExecutorIdAndMissionDefIdList {
        paramName
        type
        required
        defaultValue
        description
      }
    }
  }
}
