mutation createMissionTpl(
  $providerId: String!
  $missionTplId: String!
  $description: String
) {
  createMissionTpl(
    input: {
      missionTpl: {
        providerId: $providerId
        missionTplId: $missionTplId
        description: $description
      }
    }
  ) {
    missionTpl {
      providerId
      missionTplId
      description
    }
  }
}
