mutation deleteMissionTpl($input: DeleteMissionTplInput!) {
  deleteMissionTpl(input: $input) {
    missionTpl {
      executorId
      missionTplId
    }
  }
}

#variables: {
#  "input": {
#    "id": ""
#  }
#}
