query missionByID($id: ID!) {
  mission(id: $id) {
    providerId
    missionTplId
    missionId
    missionStatus
    assetId
    schedType
    schedDate
    assetByProviderIdAndAssetId {
      className
    }
    description
    argumentsByProviderIdAndMissionTplIdAndMissionIdList {
      id
      paramName
      paramValue
      paramUnits
    }

    missionTplByProviderIdAndMissionTplId {
      providerByProviderId {
        httpEndpoint
        apiType
        canValidate
        usesSched
        usesUnits
        descriptionFormat
      }
    }
  }
}
