query missions($executorId: String!) {
  allMissionsList(condition: {
    executorId: $executorId
  }) {
    nodeId
    executorId
    missionId
    missionDefId
    assetId
    name
    description
    startDate
    endDate
    geometry
  }
}
