query missions($executorId: String!) {
  allMissionsList(condition: {
    executorId: $executorId
  }) {
    id
    executorId
    missionDefId
    missionId
    missionStatus
    assetId
    description
    startDate
    endDate
    geometry
  }
}
