query missionTpls($providerId: String!) {
  allMissionTplsList(condition: {
    providerId: $providerId
  }) {
    id
    providerId
    providerByProviderId {
      descriptionFormat
    }
    missionTplId
    description
    missionTplAssetClassesByProviderIdAndMissionTplIdList {
      assetClassName
      assetClassByProviderIdAndAssetClassName {
        assetsByProviderIdAndClassNameList {
          assetId
        }
      }
    }
  }
}
