mutation(
  $executorId: String!
  $missionDefId: String!
  $description: String
) {
  createMissionDef(
    input: {
      missionDef: {
        executorId: $executorId
        missionDefId: $missionDefId
        description: $description
      }
    }
  ) {
    missionDef {
      executorId
      missionDefId
      description
    }
  }
}
