mutation(
  $name: String!
  $type: String!
  $required: Boolean!
  $description: String
  $default_value: String
) {
  insert_parameters(
    objects: [
      {
        name: $name
        type: $type
        required: $required
        description: $description
        default_value: $default_value
      }
    ]
  ) {
    affected_rows
  }
}
