mutation deleteParameter($input: DeleteParameterInput!) {
  deleteParameter(input: $input) {
    parameter {
      providerId
      missionTplId
      paramName
      type
      required
      defaultValue
      description
    }
  }
}

#variables: {
#  "input": {
#    "id": ""
#  }
#}
