mutation(
  $name: String!
  $type: String!
  $required: Boolean!
  $description: String
  $defaultValue: String
) {
  insert_parameter(
    objects: [
      {
        name: $name
        type: $type
        required: $required
        description: $description
        defaultValue: $defaultValue
      }
    ]
  ) {
    affected_rows
  }
}
