mutation updateParameter($input: UpdateParameterInput!) {
  updateParameter(input: $input) {
    parameter {
      executorId
      missionTplId
      paramName
      type
      required
      defaultValue
      defaultUnits
      description
    }
  }
}

# variables: {
#  "input": {
#    "id": "asasasas",
#    "parameterPatch": {
#      "paramName":         ".."
#      "type":         ".."
#      "required":     ".."
#      "defaultValue": ".."
#      "defaultUnits": ".."
#      "description":  ".."
#    }
#  }
#}
