query ($executorId: String!, $missionTplId: String!, $paramName: String!) {
  parameterByExecutorIdAndMissionTplIdAndParamName(
    executorId: $executorId,
    missionTplId: $missionTplId,
    paramName: $paramName
  ) {
    id
    executorId
    missionTplId
    paramName
    type
    required
    defaultValue
    description
  }
}
