mutation(
  $executorId: String!
  $missionTplId: String!
  $paramName: String!
  $type: String!
  $required: Boolean!
  $defaultValue: String
  $description: String
) {
  createParameter(
    input: {
      parameter: {
        executorId: $executorId
        missionTplId: $missionTplId
        description: $description
        paramName: $paramName
        type: $type
        defaultValue: $defaultValue
        required: $required
      }
    }
  ) {
    parameter {
      executorId
      missionTplId
      description
      paramName
      type
      required
    }
  }
}
