query ($executorId: String!, $missionDefId: String!, $paramName: String!) {
  parameterByExecutorIdAndMissionDefIdAndName(
    executorId: $executorId,
    missionDefId: $missionDefId,
    name: $paramName
  ) {
    id
    executorId
    missionDefId
    name
    type
    required
    defaultValue
    description
  }
}
