query ($executorId: String!, $missionDefId: String!, $paramName: String!) {
  parameterByExecutorIdAndMissionDefIdAndParamName(
    executorId: $executorId,
    missionDefId: $missionDefId,
    paramName: $paramName
  ) {
    id
    executorId
    missionDefId
    paramName
    type
    required
    defaultValue
    description
  }
}
