mutation($executorId: String!, $taskDefId: String!, $assetClassName: String!) {
  createTaskdefAssetClass(
    input: {
      taskdefAssetClass: {
        taskDefId: $taskDefId
        executorId: $executorId
        assetClassName: $assetClassName
      }
    }
  ) {
    taskdefAssetClass {
      executorId
      taskDefId
      assetClassName
    }
  }
}
