query task($planId: String!, $taskId: String!) {
  taskByPlanIdAndTaskId(planId: $planId, taskId: $taskId) {
    nodeId
    planId
    taskId
    name
    assetId
    taskDefId
    description
    executorId
    argumentsByPlanIdAndTaskIdList {
      nodeId
      paramName
      paramValue
      parameterByExecutorIdAndTaskDefIdAndParamName {
        type
        required
        defaultValue
        description
      }
    }
    taskDefByExecutorIdAndTaskDefId {
      parametersByExecutorIdAndTaskDefIdList {
        name
        type
        required
        defaultValue
        description
      }
    }
  }
}
