query task_defs($executorId: String!, $taskDefId: String!) {
  task_defs(where: { _and: [
    {executorId: {_eq: $executorId}},
    {taskDefId: {_eq: $taskDefId}}
  ]}) {
    executorId
    description
    executorAssetclasssByexecutorid {
      asset_className
      assetclassesByassetclassname {
        className
        description
      }
    }
  }
}
