mutation(
  $taskId: String!
  $executorId: String!
  $taskDefId: String!
  $assetId: String!
  $name: String!
  $description: String
) {
  createTask(
    input: {
      task: {
        taskId: $taskId
        executorId: $executorId
        taskDefId: $taskDefId
        assetId: $assetId
        name: $name
        description: $description
      }
    }
  ) {
    task {
      taskId
      executorId
      taskDefId
      assetId
      name
      description
      startDate
      endDate
      geometry
    }
  }
}
