query ($executorId: String!, $taskDefId: String!) {
  taskDefByExecutorIdAndTaskDefId(executorId: $executorId, taskDefId: $taskDefId) {
    nodeId
    taskDefId
    description
    taskdefAssetClassesByExecutorIdAndTaskDefIdList {
      nodeId
      assetClassName
      assetClassByAssetClassName {
        description
      }
    }
    parametersByExecutorIdAndTaskDefIdList {
      nodeId
      name
      type
      required
      defaultValue
      description
    }
  }
}
