query task($taskId: String!) {
  taskByTaskId(taskId: $taskId) {
    nodeId
    taskId
    name
    assetId
    taskDefId
    description
    executorId
    argumentsByTaskIdList {
      nodeId
      paramName
      paramValue
      parameterByExecutorIdAndTaskDefIdAndParamName {
        type
        required
        defaultValue
        description
      }
    }
    taskDefByExecutorIdAndTaskDefId {
      parametersByExecutorIdAndTaskDefIdList {
        name
        type
        required
        defaultValue
        description
      }
    }
  }
}
