mutation($providerId: String!, $unitName: String!, $abbreviation: String, $baseUnit: String) {
  createUnit(
    input: {
      unit: {
        providerId: $providerId
        unitName: $unitName
        abbreviation: $abbreviation
        baseUnit: $baseUnit
      }
    }
  ) {
    unit {
      providerId
      unitName
      abbreviation
      baseUnit
    }
  }
}
