name: MXM tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
          cache-dependency-path: |
            server/yarn.lock
            webapp/yarn.lock
      - name: Install jest
        run: yarn global add jest
      - name: Build and test server
        run: (cd server && yarn && npm run test:unit)
      - name: Build and test webapp
        run: (cd webapp && yarn && npm run test:unit)

