name: mxm-server CI

on:
  push:
    paths: ['mxm-server/**']
  pull_request:
    paths: ['mxm-server/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mxm-server

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, check format, and test
        run: ./mvnw clean spotless:check test
